services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hetu
      POSTGRES_DB: operator_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 50
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6369:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - app-network

  aos_operator:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hetu
      POSTGRES_DB: operator_db
      POSTGRES_PORT: 5432
      REDIS_URL: "redis://:@redis:6369"
      WORKER_URL: "http://worker:21001"
      DISPATCHER_URL: ""
      DISPATCHER_ADDRESS: ""
      CHAIN_RPC_URL: "https://ethereum-holesky-rpc.publicnode.com"
      VRF_RANGE_CONTRACT: "0x27e4384ecc11810c2F49914390052b22c4e3CcC0"
      NODE_ID: ""
      NODE_TYPE: "opml"
      SIGNER_KEY: ""
      VRF_KEY: ""
    ports:
      - "21001:21001"
      - "9000:9000"
    restart: always
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
